import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="./posts/firstPost">firstPost</Link>
      <div>
        <Image src="/ryocode.png" alt="コアラ" width={100} height={100} />
      </div>
    </>
  );
}
